Update docker_push.yaml

diff --git a/.github/workflows/docker_push.yaml b/.github/workflows/docker_push.yaml
--- a/.github/workflows/docker_push.yaml
+++ b/.github/workflows/docker_push.yaml
@@ -61,7 +61,7 @@ jobs:
             echo "File before update:"
             cat kubernetes-manifests/resume-frontend-deployment.yaml
             
-            sed -i -E '/containers:/,/image:/ s|image:.*|image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfolio-app-images/resume-frontend:${{ github.sha }}|' kubernetes-manifests/resume-frontend-deployment.yaml
+            sed -i 's|\(image:.*resume-frontend:\).*|\1${{ github.sha }}|' kubernetes-manifests/resume-frontend-deployment.yaml || { echo "Error updating deployment manifest"; exit 1; }
             
             echo "File after update:"
             cat kubernetes-manifests/resume-frontend-deployment.yaml
